version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm test
      - run:
          name: Deploy Master to Heroku
          command: |
            node_modules/.bin/webpack
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
